### PR TITLE
#162969995 User can view the top questions on meetups they're scheduled to attend.

### PR DESCRIPTION
**Pull request by cod3smith**
#### What does this PR do?
This PR contains the UI template that enables the user to view the top questions asked (questions with the most upvotes) in meetups they are scheduled to attend.

#### Description of Task to be completed?
- [x] Add a top questions table.
- [x] Add styling to top questions table.

#### How should this be manually tested?
To manually test this:
1. Clone this repository using:
`git clone https://github.com/KelynPNjeri/Questioner.git`
2. Through your terminal, navigate to the location to which you cloned the repository.
3. Open the cloned repository.
4. From your terminal, change branches to `ft-top-questions-162969995` branch using
`git checkout ft-top-questions-162969995`
5. Open the HTML folder under the UI folder.
6. Run the dashboard.html file in your browser.

#### Any background context you want to provide?
This is only a UI template for the Questioner web app. It does not contain any functionality whatsoever.

#### What are the relevant pivotal tracker stories?
[#162969995](https://www.pivotaltracker.com/story/show/162969995)

#### Screenshots (if appropriate)
dash1
dash2

### CODE REVIEW

**Comment by SolomonMacharia** [comment]
The UI looks nice.

**Comment by SolomonMacharia** [comment]
You may also consider adding the link to the PT story.

**Comment by SolomonMacharia** [comment]
And also some padding to space out the asked questions section.

**Comment by cod3smith** [comment]
> And also some padding to space out the asked questions section.

Thanks for the feedback I will implement that.

**Pull request merged**
