### PR TITLE
#163004073 Create Meetup Page.

### PR DESCRIPTION
**Pull request by cod3smith**
#### What does this PR do?
This PR contains the UI template for the Questioner Web app.

#### Description of Task to be completed?
- [x] Create a page where a user can view all the meetups.

#### How should this be manually tested?
To manually test this:
1. Clone this repository using:
`git clone https://github.com/KelynPNjeri/Questioner.git`\
2. Through your terminal, navigate to the location to which you cloned the repository.
3. Open the closed repository.
4. From your terminal, change branches to the `ft-meetup-page-163004073`using:
`git checkout ft-meetup-page-163004073`.
5. Navigate into the UI folder and into the html folder.
6. Run the meetup.html file in your browser.

#### Any background context you want to provide?
This is just a UI template for the Questioner Web App. It has no functionality whatsoever.

#### What are the relevant pivotal tracker stories?
[#163004073](https://www.pivotaltracker.com/story/show/163004073)

#### Screenshots (if appropriate)
meetuppage

### CODE REVIEW

**Comment by wachiranduati** [comment]
you merged into the wrong branch....should be gh-pages not the develop branch..

**Comment by cod3smith** [comment]
@wachiranduati in the document they say that we should create a PR for each feature then merge into develop branch

**Comment by SolomonMacharia** [comment]
Nice outline.

**Comment by jackiegitari1234** [comment]
Looks great

**Comment by cod3smith** [comment]
Thanks @jackiegitari1234 and @SolomonMacharia

**Pull request merged**
