### PR TITLE
#162982314 Create Landing Page.

### PR DESCRIPTION
**Pull request by cod3smith**
#### What does this PR do?
This PR has the landing page for the Questioner Web app.

#### Description of Task to be completed?
- [x] Create a landing page which should be the first page.

#### How should this be manually tested?
To manually test this:
- Clone this repository using:
`git clone https://github.com/KelynPNjeri/Questioner.git`
- Navigate to the location to which you cloned the repository using your terminal.
- From your terminal change branches to the `ft-landing-page-162982314` branch using `git checkout ft-landing-page-162982314`
- Open the UI folder in the Questioner folder and run `index.html` in your browser.

#### Any background context you want to provide?
This is purely a UI template and it doesn't contain the core functionality of the web app.

#### What are the relevant pivotal tracker stories?
[#162982314](https://www.pivotaltracker.com/story/show/162982314)

#### Screenshots (if appropriate)
landingpage

### CODE REVIEW

**Comment by wachiranduati** [comment]
looks dope..

**Comment by cod3smith** [comment]
> looks dope..

Thanks

**Comment by Deekerubo** [comment]
Looks Good. You can make the  **view more Events** have a bigger font for it to be visible

**Comment by cod3smith** [comment]
Thanks, @Deekerubo I will work on that immediately.

**Comment by jackiegitari1234** [comment]
Nice UI

**Comment by SolomonMacharia** [comment]
Looks great.

**Pull request merged**
